config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'

    root to: 'works#index'
    resources :work_blocks
    resources :users
    resources :tags
    resources :tabs
    resources :sentences
    resources :media
    resources :likes
    resources :embeds
  end

  get 'start', to: 'others#landing_page'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'terms', to: 'others#terms'
  get 'privacy', to: 'others#privacy'
  get 'how_to', to: 'others#how_to'

  root 'works#index'

  resources :works, only: %i[new create show edit update destroy] do
    resources :work_blocks
    collection do
      get 'likes'
    end
  end

  resources :users, only: %i[new create show edit update destroy]
  resources :likes, only: %i[create destroy]
end

app/models/work.rb
class Work < ApplicationRecord
  mount_uploader :thumbnail, ThumbnailUploader
  validates :title, presence: true, length: { maximum: 255 }
  validates :summary, presence: true, length: { maximum: 255 }
  validates :status, presence: true

  belongs_to :user
  has_many :work_blocks, inverse_of: :work
  has_many :sentences, through: :work_blocks, source: :blockable, source_type: 'Sentence'
  has_many :media, through: :work_blocks, source: :blockable, source_type: 'Medium'
  has_many :embeds, through: :work_blocks, source: :blockable, source_type: 'Embed'

  has_many :work_tag_relations
  has_many :tags, through: :work_tag_relations, dependent: :destroy

  enum status: { publish: 0, hide: 1 }

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    ["title", "summary"]
end
end

app/controllers/admin/works_controller.rb
module Admin
  class WorksController < Admin::ApplicationController
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_current_user_work, only: %i[edit update destroy]
  skip_before_action :require_login, only: %i[new create show index]

  def new
    @work = Work.new
  end

  def create
    @work = current_user.works.build(work_params)
    tag_list = params[:work][:tag_name].split(',').uniq
    if @work.valid?
      @work.save
      @work.save_tag(tag_list)
      redirect_to @work
    else
      @tags = params[:work][:tag_name]
      flash.now[:danger]
      render :new
    end
  end

  def index
    if params[:tag_name]
      tag = Tag.find_by(name: params[:tag_name])
      @q = tag.works.ransack(params[:q])
      @works = @q.result(distinct: true).includes(:user).order(created_at: :desc)
    else
      @q = Work.ransack(params[:q])
      @works = @q.result(distinct: true).includes(:user).order(created_at: :desc)
    end
  end

  def show
    @work = Work.find(params[:id])
    @storys = @work.work_blocks.where(tab_id: 1).preload(:blockable)
    @characters = @work.work_blocks.where(tab_id: 2).preload(:blockable)
    @logs = @work.work_blocks.where(tab_id: 3).preload(:blockable).order(id: :DESC)
    @work_blocks = @work.work_blocks.preload(:blockable)
  end

  def edit
    @tags = @work.tags.pluck(:name).join(',')
  end

  def update
    tag_list = params[:work][:tag_name].split(',').uniq
    if @work.update(work_params)
      @work.save_tag(tag_list)
      redirect_to @work
    else
      flash.now['danger']
      render :edit
    end
  end

  def destroy
    @work.destroy!
    redirect_to root_path
  end

  def likes
    @q = current_user.like_works.ransack(params[:q])
    @like_works = @q.result(distinct: true).includes(:user).order(created_at: :desc)
  end

  private

  def set_current_user_work
    @work = current_user.works.find(params[:id])
  end

  def work_params
    params.require(:work).permit(:title, :summary, :thumbnail, :thumbnail_cache, :status)
  end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_crud_menus.html.erb
<div class="inline-flex rounded-md shadow-sm">
  <%= button_to '編集', edit_work_path(work), method: :get, class: "py-2 px-4 text-sm font-medium text-gray-700 bg-white rounded-l-lg border border-gray-200 hover:bg-gray-100 focus:z-10 focus:ring-2 focus:ring-gray-700 focus:text-gray-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-500 dark:focus:text-white" %>
  <%= button_to '削除', work, method: :delete, form: { data: { turbo_confirm: "削除しますか？" }}, class: "py-2 px-4 text-sm font-medium text-gray-900 bg-white rounded-r-md border border-gray-200 hover:bg-gray-100 hover:text-gray-700 focus:z-10 focus:ring-2 focus:ring-gray-700 focus:text-gray-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-500 dark:focus:text-white" %>
</div>

app/views/works/_form.html.erb
<%= form_with model: work, local: true, class: 'w-full max-w-xs mx-auto' do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
  <div class="mb-6"><!------ 画像の添付 ------>
    <%= f.label :title, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= f.text_field :title, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-500 focus:border-gray-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-500 dark:focus:border-gray-500' %>
  </div>

  <!------ あらすじ ------>
  <div class="mb-6">
    <%= f.label :summary, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= f.text_area :summary, rows: 2, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-500 focus:border-gray-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-500 dark:focus:border-gray-500' %>
  </div>

  <!------ 画像の添付 ------>
  <div class="mb-6">
    <%= f.label :thumbnail, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= f.file_field :thumbnail, onchange: "thumbnailImage(this);", class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-500 focus:border-gray-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-500 dark:focus:border-gray-500' %>
  </div>

<!------ タグ ------>
  <div class="mb-6">
    <%= f.label :tag_name, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= f.text_field :tag_name, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-500 focus:border-gray-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-500 dark:focus:border-gray-500', placeholder: ',で区切って入力してください', value: @tags %>
  </div>

  <!------ 画像プレビュー ------>
  <div id="thumbnail" class="mb-6" >
    <img id="thumbnail_preview" class="mb-3" width="600">
  </div>
  <% if work.thumbnail.present? %> 
    <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white font-bold">現在登録されている画像</label>
    <%= image_tag work.thumbnail.url, size: '600x400', class: "mb-2" %>
  <% end %>

  <div class="flex items-start mb-6">
    <div class="flex items-center h-5">
      <%= check_box :work, :status, {class: "w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-gray-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-gray-600 dark:ring-offset-gray-800"}, 'hide', 'publish' %>
    </div>
    <label for="remember" class="ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">トップページに作品を表示しない<br>※ユーザーページには作品が表示されます</label>
  </div>

  <div class='flex items-center justify-between'>
    <%= f.submit '送信', class:  "text-white bg-gray-900 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800" %>
  </div>
<% end %>


<!------ プレビュー表示用の JavaScript ------>
<script>
  function thumbnailImage(obj){
      var fileReader = new FileReader();
      fileReader.onload = (function() {
        document.getElementById('thumbnail_preview').src = fileReader.result;
      });
      fileReader.readAsDataURL(obj.files[0]);
  }
</script>

app/views/works/_like.html.erb
<%= button_to likes_path(work_id: work.id), id: "js-like-button-for-work-#{work.id}", class:"float-right", data: { "turbo-method": :post }, remote: true do %>
  <svg class="w-6 h-6 dark:text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"></path></svg>
<% end %>

app/views/works/_like_button.html.erb
<% if current_user&.like?(work) %>
  <%= render 'works/unlike', { work: work } %>
<% else %>
  <%= render 'works/like', { work: work  }%>
<% end %>

app/views/works/_unlike.html.erb
<%= button_to like_path(current_user.likes.find_by(work_id: work.id)), id: "js-like-button-for-work-#{work.id}", class:"float-right", method: :delete, remote: true do %>
  <svg class="w-6 h-6 dark:text-white" fill="all" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"></path></svg>
<% end %>

app/views/works/_work.html.erb
<div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow-md dark:bg-gray-800 dark:border-gray-700">
    <%= image_tag work.thumbnail.url, class: "rounded-t-lg", size: "600x400"%>
    <div class='mr10 float-right'>
      <% if current_user&.own?(work) %>
        <%= render 'works/crud_menus', work: work %>
      <% else %>
        <%= render 'works/like_button', work: work %>
      <% end %>
    </div>
    <div class="p-5">
        <%= link_to work.title, work_path(work), class: "mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white" %>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= work.summary %></p>
        <%= link_to "著者: #{work.user.name}", user_path(work.user.id), class: "mb-3 font-normal text-gray-700 dark:text-gray-400"%><br>
        <% work.tags.each do |tag| %>
          <%= link_to tag.name, root_path(tag_name: tag.name),type: "button", class: "py-2.5 px-5 mr-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-full border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700" %>
        <% end %></li>
    </div>
</div>

app/views/works/edit.html.erb
<div class="w-full max-w-xs mx-auto">
<p class="text-gray-900 text-2xl dark:text-white font-bold mb-3">作品を編集する</p>
  <div class="md:flex md:items-center mb-6">
    <div class="mb-4">
      <%= render 'form', { work: @work } %>
    </div>
  </div>
</div>

app/views/works/index.html.erb
<section class="bg-white dark:bg-gray-900 w-full">
  <%= render 'shared/search', url: root_path %>
  <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6 ">
      <div class="grid gap-8 mb-6 lg:mb-16 md:grid-cols-3">
              <% if @works.present? %>
              <%= render @works %>
             <% else %>
              <p><%= t('.no_result') %></p>
            <% end %>
      </div>
  </div>
</section>

app/views/works/likes.html.erb
<section class="bg-white dark:bg-gray-900 w-full">
<%= render 'shared/search', url: root_path %>
  <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6 ">
      <div class="grid gap-8 mb-6 lg:mb-16 md:grid-cols-3">
              <% if @like_works.present? %>
              <%= render @like_works %>
             <% else %>
              <p><%= t('.no_result') %></p>
            <% end %>
      </div>
  </div>
</section>

app/views/works/new.html.erb
<div class="w-full max-w-xs mx-auto">
  <p class="text-gray-900 text-2xl dark:text-white font-bold mb-3">作品を追加する</p>
  <div class="md:flex md:items-center mb-6">
    <%= render 'form', { work: @work } %>
  </div>
</div>

app/views/works/show.html.erb
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <!-- 作品のサムネ、題名とか -->
      <article class="card">
        <div class="card-body">
          <div class='row'>
            <div >
              <%= image_tag @work.thumbnail.url, class: 'mx-auto bg-contain block w-full' %>
            </div>
            <div class='col-md-9'>
              <div class='mb-3 text-3xl font-bold'>
                <%= @work.title %>
              </div>
            </div>
          </div>
        </div>
      </article>


      <!-- タブ見出し -->
      <div class="mb-4 border-b border-gray-200 dark:border-gray-700">
          <ul class="flex flex-wrap -mb-px text-sm font-medium text-center" id="myTab" data-tabs-toggle="#myTabContent" role="tablist">
              <li class="mr-2" role="presentation">
                  <button class="inline-block p-4 rounded-t-lg border-b-2" id="summary-tab" data-tabs-target="#summary" type="button" role="tab" aria-controls="summary" aria-selected="false">概要</button>
              </li>
              <li class="mr-2" role="presentation">
                  <button class="inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" id="story-tab" data-tabs-target="#story" type="button" role="tab" aria-controls="story" aria-selected="false">ストーリー</button>
              </li>
              <li class="mr-2" role="presentation">
                  <button class="inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" id="character-tab" data-tabs-target="#character" type="button" role="tab" aria-controls="character" aria-selected="false">キャラ</button>
              </li>
              <li role="presentation">
                  <button class="inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" id="log-tab" data-tabs-target="#log" type="button" role="tab" aria-controls="log" aria-selected="false">ログ</button>
              </li>
          </ul>
      </div>

      <div id="myTabContent">
          <!-- 概要タブ中身 -->
          <div class="hidden p-4 bg-gray-50 rounded-lg dark:bg-gray-800" id="summary" role="tabpanel" aria-labelledby="summary-tab">
            <ul class="list-inline">
              <li class="list-inline-item"><%= link_to "author: #{@work.user.name}", user_path(@work.user.id) %></li>
              <li class="list-inline-item">登録:<%= l @work.created_at, format: :long %></li>
              <li class="list-inline-item">更新:<%= l @work.updated_at, format: :long %></li>
              <li class="list-inline-item">タグ:
                <% @work.tags.each do |tag| %>
                  <%= link_to tag.name, works_path(tag_name: tag.name),type: "button", class: "py-2.5 px-5 mr-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-full border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700" %>
                <% end %></li>
              <p><%= simple_format(@work.summary) %></p>
            <div class='mr10 mt-5'>
              <% if current_user&.own?(@work) %>
                <%= render 'crud_menus', work: @work %>
              <% end %>
            </div>
            </ul>
            </div>

          <!-- ストーリータブ中身 -->
          <div class="hidden p-4 bg-gray-50 rounded-lg dark:bg-gray-800" id="story" role="tabpanel" aria-labelledby="story-tab">
              <% if current_user&.own?(@work) %>
                <%= render 'work_blocks/modal' %>
              <% end %>
              <ol class="relative border-l border-gray-200 dark:border-gray-700"> 
              <% @storys.each do |work_block| %>
                <%= render 'work_blocks/work_block', work: @work, work_blocks: @work_blocks, work_block: work_block %>
              <% end %>
              </ol>
          </div>

          <!-- キャラクタータブ中身 -->
          <div class="hidden p-4 bg-gray-50 rounded-lg dark:bg-gray-800" id="character" role="tabpanel" aria-labelledby="character-tab">
              <% if current_user&.own?(@work) %>
                <%= render 'work_blocks/modal_character' %>
              <% end %>
              <ol class="relative border-l border-gray-200 dark:border-gray-700"> 
              <% @characters.each do |work_block| %>
                <%= render 'work_blocks/work_block', work: @work, work_blocks: @work_blocks, work_block: work_block %>
              <% end %>
              </ol>
          </div>

          <!-- ログタブ中身 -->
          <div class="hidden p-4 bg-gray-50 rounded-lg dark:bg-gray-800" id="log" role="tabpanel" aria-labelledby="log-tab">
              <% if current_user&.own?(@work) %>
                <%= render 'work_blocks/modal_log' %>
              <% end %>
              <ol class="relative border-l border-gray-200 dark:border-gray-700"> 
              <% @logs.each do |work_block| %>
                <%= render 'work_blocks/work_block', work: @work, work_blocks: @work_blocks, work_block: work_block %>
              <% end %>
              </ol>
          </div>
      </div>

    </div>
  </div>

</div>