config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'

    root to: 'works#index'
    resources :work_blocks
    resources :users
    resources :tags
    resources :tabs
    resources :sentences
    resources :media
    resources :likes
    resources :embeds
  end

  get 'start', to: 'others#landing_page'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'terms', to: 'others#terms'
  get 'privacy', to: 'others#privacy'
  get 'how_to', to: 'others#how_to'

  root 'works#index'

  resources :works, only: %i[new create show edit update destroy] do
    resources :work_blocks
    collection do
      get 'likes'
    end
  end

  resources :users, only: %i[new create show edit update destroy]
  resources :likes, only: %i[create destroy]
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :name,   presence: true, length: { maximum: 255 }
  validates :email,  presence: true, uniqueness: true
  validates :role,   presence: true

  has_many :works, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_works, through: :likes, source: :work

  enum role: { general: 0, admin: 1 }

  # 自分の作成したオブジェクトか確認する
  def own?(object)
    id == object.user_id
  end

  # 　自分かどうか確認する
  def me?(object)
    id == object.id
  end

  def like(work)
    like_works << work
  end

   def unlike(work)
    like_works.destroy(work)
  end

  def like?(work)
    like_works.include?(work)
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_current_user, only: %i[edit update destroy]
  skip_before_action :require_login, only: %i[new create show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_back_or_to root_path
    else
      flash.now[:danger]
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @works = Work.where(user_id: params[:id])
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      flash.now[:danger]
      render :edit
    end
  end

  def destroy
    @user.destroy!
    redirect_to root_path
  end

  private

  def set_current_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :bio, :avatar, :avatar_cache)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_with model: @user, local: true, class: 'w-full max-w-xs mx-auto' do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
  <!------ ユザネ ------>
  <div class="mb-6">
    <%= f.label :name, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= f.text_field :name, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-500 focus:border-gray-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-500 dark:focus:border-gray-500' %>
  </div>

  <!------ プロフィール ------>
  <div class="mb-6">
    <%= f.label :bio, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= f.text_area :bio, rows: 3, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-500 focus:border-gray-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-500 dark:focus:border-gray-500' %>
  </div>

  <!------ 画像の添付 ------>
  <div class="mb-6">
    <%= f.label :avatar, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= f.file_field :avatar, onchange: "avatarImage(this);", class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-500 focus:border-gray-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-500 dark:focus:border-gray-500' %>
  </div>

  <!------ 画像プレビュー ------>
  <div id="avatar" class="mb-6" >
      <img id="avatar_preview" class="mb-3" width="200">
    </div>
  <% if @user.avatar.present? %> 
    <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white font-bold">現在登録されている画像</label>
    <%= image_tag @user.avatar_url, size: '200x200', class: "mb-2" %>
  <% end %>

  <div class='flex items-center justify-between'>
    <%= f.submit '送信', class:  "text-white bg-gray-900 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800" %>
  </div>
<% end %>
</div>

<!------ プレビュー表示用の JavaScript ------->
<script>
  function avatarImage(obj){
      var fileReader = new FileReader();
      fileReader.onload = (function() {
        document.getElementById('avatar_preview').src = fileReader.result;
      });
      fileReader.readAsDataURL(obj.files[0]);
  }
</script>

app/views/users/new.html.erb
<div class="w-full max-w-xs mx-auto">
  <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    <div class="mb-4">
      <div class="text-3xl font-bold pb-4">
        <h1>新規登録</h1>
      </div>
      <%= form_with model: @user, local: true do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
        <div class="block text-black-700 text-sm font-bold mb-2">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="block text-black-700 text-sm font-bold mb-2">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="block text-black-700 text-sm font-bold mb-2">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control'%>
        </div>
        <div class="block text-black-700 text-sm font-bold mb-2">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <p><%= link_to '利用規約', terms_path, target: :_blank, rel: 'noopener noreferrer', class: 'underline' %></li>に同意して</p>
        <div class='flex items-center justify-between'>
          <%= f.submit '新規登録', class: "text-white bg-gray-900 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
        </div>
      <% end %>
      <div class='ttext-center text-gray-500 text-xs'>
        <%= link_to 'すでに登録済みの方はこちら', login_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container pt-3">
  <!-- プロフィール -->
  <section class="bg-white dark:bg-gray-900">
    <div class="grid max-w-screen-xl px-4 py-1 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12">
      <div class="lg:mt-0 lg:col-span-5 lg:flex">
        <%= image_tag @user.avatar.url, size: '200x200', class: 'w-100 h-100 rounded-full mb-4' %>
      </div>

      <div class="mr-auto place-self-center lg:col-span-7">
        <h1 class="max-w-2xl mb-4 text-2xl font-extrabold tracking-tight leading-none md:text-2xl xl:text-2xl dark:text-white inline-flex w-24">
          <%= @user.name %>
        </h1>
        <% if current_user&.me?(@user) %>
          <%= link_to 'ユーザー編集', edit_user_path, class: 'inline-flex items-center justify-center px-4 py-3 text-base font-medium text-center text-gray-900 border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 dark:text-white dark:border-gray-700 dark:hover:bg-gray-700 dark:focus:ring-gray-800' %>
        <% end %>
        <p class="max-w-2xl mt-2 mb-3 font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400"><%= @user.bio %></p>
      </div>
    </div>
  </section>
    <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700">

  <!-- 作品一覧 -->
<section class="bg-white dark:bg-gray-900">
  <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6 ">
      <div class="grid gap-8 mb-6 lg:mb-16 md:grid-cols-3">
        <% if @works.present? %>
          <%= render @works %>
        <% else %>
            <p><%= t('.no_result') %></p>
        <% end %>
      </div>
  </div>
</section>