config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'

    root to: 'works#index'
    resources :work_blocks
    resources :users
    resources :tags
    resources :tabs
    resources :sentences
    resources :media
    resources :likes
    resources :embeds
  end

  get 'start', to: 'others#landing_page'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'terms', to: 'others#terms'
  get 'privacy', to: 'others#privacy'
  get 'how_to', to: 'others#how_to'

  root 'works#index'

  resources :works, only: %i[new create show edit update destroy] do
    resources :work_blocks
    collection do
      get 'likes'
    end
  end

  resources :users, only: %i[new create show edit update destroy]
  resources :likes, only: %i[create destroy]
end

app/models/work_block.rb
class WorkBlock < ApplicationRecord
  belongs_to :work
  belongs_to :blockable, polymorphic: true, dependent: :destroy
  belongs_to :tab

  class << self
    def blockable_types
      %w[Sentence Medium Embed]
    end

    def valid_blockable_type?(type)
      blockable_types.include?(type.to_s.classify)
    end
  end

  def sentence?
    blockable.is_a?(Sentence)
  end

  def medium?
    blockable.is_a?(Medium)
  end

  def embed?
    blockable.is_a?(Embed)
  end

  def creaet_blockable!(type, params)
    case type.to_s.classify
    when 'Sentence'
      set_work_work_block(params)
      @work_block.blockable = Sentence.create!(body: params[:body])
      @work_block.save!
    when 'Medium'
      @work = Work.find_by!(id: params[:work_id])
      params[:name].each do |name|
        @work_block = @work.work_blocks.new(tab_id: params[:tab])
        @work_block.blockable = Medium.create!(name: name)
        @work_block.save!
      end
    when 'Embed'
      set_work_work_block(params)
      @work_block.blockable = Embed.create!(identifier: params[:identifier])
      @work_block.save!
    end
    blockable
  end

  def set_work_work_block(params)
    @work = Work.find_by!(id: params[:work_id])
    @work_block = @work.work_blocks.new(tab_id: params[:tab])
  end
end

app/controllers/admin/work_blocks_controller.rb
module Admin
  class WorkBlocksController < Admin::ApplicationController
  end
end

app/controllers/work_blocks_controller.rb
class WorkBlocksController < ApplicationController
  before_action :set_work
  before_action :set_work_block, only: %i[show edit update destroy]

  def show; end

  def new
    @blockable_type = params[:blockable_type]
    @work_block = WorkBlock.new
    @tab = params[:tab]
  end

  def create
    WorkBlock.transaction do
      @work_block = @work.work_blocks.new(tab_id: params[:tab])
      blockable_type = params[:blockable_type]

      return head :bad_request if blockable_type.blank? || !WorkBlock.valid_blockable_type?(blockable_type)

      @work_block.creaet_blockable!(blockable_type, params)
    end

    redirect_to @work
  end

  def edit
    if @work_block.sentence?
      set_sentence
    elsif @work_block.medium?
      set_medium
    elsif @work_block.embed?
      set_embed
    end
  end

  def update
    WorkBlock.transaction do
      if @work_block.sentence?
        set_sentence
        @sentence.update!(sentence_params)
      elsif @work_block.medium?
        set_medium
        @medium.update!(medium_params)
      elsif @work_block.embed?
        set_embed
        @embed.update!(embed_params)
      end
    end

    redirect_to @work
  end

  def destroy
    @work_block.destroy!
    redirect_to @work
  end

  private

  def set_work
    @work = Work.find_by!(id: params[:work_id])
  end

  def set_work_block
    @work_block = @work.work_blocks.find(params[:id])
  end

  def work_block_params
    params.require(:work_block).permit(:tab_id)
  end

  def sentence_params
    params.require(:sentence).permit(:body)
  end

  def medium_params
    params.require(:medium).permit(:name)
  end

  def embed_params
    params.require(:embed).permit(:embed_type, :identifier)
  end

  def set_sentence
    @sentence = Sentence.find(@work_block.blockable_id)
  end

  def set_medium
    @medium = Medium.find(@work_block.blockable_id)
  end

  def set_embed
    @embed = Embed.find(@work_block.blockable_id)
  end
end

app/views/work_blocks/_crud_menu.html.erb
<div class="inline-flex rounded-md shadow-sm">
  <%= link_to '編集', edit_work_work_block_path(@work, work_block, blockable_type: "Sentence"), method: :get, class: "py-2 px-4 text-sm font-medium text-gray-700 bg-white rounded-l-lg border border-gray-200 hover:bg-gray-100 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white" %>
  <%= button_to '削除', work_work_block_path(@work, work_block), method: :delete, form: { data: { turbo_confirm: "削除しますか？" }}, class: "py-2 px-4 text-sm font-medium text-gray-900 bg-white rounded-r-md border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-gray-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white" %>
</div>

app/views/work_blocks/_modal.html.erb
<!-- モーダル出現ボタン -->
<button type="button" data-modal-target="crypto-modal" data-modal-toggle="crypto-modal" class="text-gray-900 bg-white hover:bg-gray-100 border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-gray-600 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:bg-gray-700">
  <svg aria-hidden="true" class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1"></path></svg>
  設定を追加
</button>

<!-- ボタン押下後表示メニュー -->
<div id="crypto-modal" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-modal md:h-full">
    <div class="relative w-full h-full max-w-md md:h-auto">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <button type="button" class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" data-modal-hide="crypto-modal">
                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>  
                <span class="sr-only">Close modal</span>
            </button>
            <!-- Modal header -->
            <div class="px-6 py-4 border-b rounded-t dark:border-gray-600">
                <h3 class="text-base font-semibold text-gray-900 lg:text-xl dark:text-white">
                    設定を追加
                </h3>
            </div>
            <!-- Modal body -->
            <div class="p-6">
                <p class="text-sm font-normal text-gray-500 dark:text-gray-400">設定をどのタイプで説明するか選んでください</p>
                <ul class="my-4 space-y-3">
                    <li>
                      <div class="flex items-center p-3 text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow dark:bg-gray-600 dark:hover:bg-gray-500 dark:text-white">
                        <%= link_to '文章', new_work_work_block_path(@work, blockable_type: "Sentence"), class: 'flex-1 ml-3 whitespace-nowrap' %>
                      </div>
                    </li>
                    <li>
                      <div class="flex items-center p-3 text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow dark:bg-gray-600 dark:hover:bg-gray-500 dark:text-white">
                        <%= link_to '画像', new_work_work_block_path(@work, blockable_type: "Medium"), class: 'flex-1 ml-3 whitespace-nowrap' %>
                      </div>
                    </li>
                    <li>
                      <div class="flex items-center p-3 text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow dark:bg-gray-600 dark:hover:bg-gray-500 dark:text-white">
                        <%= link_to 'ツイート', new_work_work_block_path(@work, blockable_type: "Embed"), class: 'flex-1 ml-3 whitespace-nowrap' %>
                      </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/work_blocks/_modal_character.html.erb
<!-- モーダル出現ボタン -->
<button type="button" data-modal-target="chara-modal" data-modal-toggle="chara-modal" class="text-gray-900 bg-white hover:bg-gray-100 border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-gray-600 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:bg-gray-700">
  <svg aria-hidden="true" class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1"></path></svg>
  キャラクターを追加
</button>

<!-- ボタン押下後表示メニュー -->
<div id="chara-modal" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-modal md:h-full">
    <div class="relative w-full h-full max-w-md md:h-auto">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <button type="button" class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" data-modal-hide="chara-modal">
                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>  
                <span class="sr-only">Close modal</span>
            </button>
            <!-- Modal header -->
            <div class="px-6 py-4 border-b rounded-t dark:border-gray-600">
                <h3 class="text-base font-semibold text-gray-900 lg:text-xl dark:text-white">
                    設定を追加
                </h3>
            </div>
            <!-- Modal body -->
            <div class="p-6">
                <p class="text-sm font-normal text-gray-500 dark:text-gray-400">設定をどのタイプで説明するか選んでください</p>
                <ul class="my-4 space-y-3">
                    <li>
                      <div class="flex items-center p-3 text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow dark:bg-gray-600 dark:hover:bg-gray-500 dark:text-white">
                        <%= link_to '文章', new_work_work_block_path(@work, blockable_type: "Sentence", tab: 2), class: 'flex-1 ml-3 whitespace-nowrap' %>
                      </div>
                    </li>
                    <li>
                      <div class="flex items-center p-3 text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow dark:bg-gray-600 dark:hover:bg-gray-500 dark:text-white">
                        <%= link_to '画像', new_work_work_block_path(@work, blockable_type: "Medium", tab: 2), class: 'flex-1 ml-3 whitespace-nowrap' %>
                      </div>
                    </li>
                    <li>
                      <div class="flex items-center p-3 text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow dark:bg-gray-600 dark:hover:bg-gray-500 dark:text-white">
                        <%= link_to 'ツイート', new_work_work_block_path(@work, blockable_type: "Embed", tab: 2), class: 'flex-1 ml-3 whitespace-nowrap' %>
                      </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/work_blocks/_modal_log.html.erb
<!-- モーダル出現ボタン -->
<button type="button" data-modal-target="log-modal" data-modal-toggle="log-modal" class="text-gray-900 bg-white hover:bg-gray-100 border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-gray-600 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:bg-gray-700">
  <svg aria-hidden="true" class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1"></path></svg>
  ログを追加
</button>

<!-- ボタン押下後表示メニュー -->
<div id="log-modal" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-modal md:h-full">
    <div class="relative w-full h-full max-w-md md:h-auto">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <button type="button" class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" data-modal-hide="log-modal">
                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>  
                <span class="sr-only">Close modal</span>
            </button>
            <!-- Modal header -->
            <div class="px-6 py-4 border-b rounded-t dark:border-gray-600">
                <h3 class="text-base font-semibold text-gray-900 lg:text-xl dark:text-white">
                    設定を追加
                </h3>
            </div>
            <!-- Modal body -->
            <div class="p-6">
                <p class="text-sm font-normal text-gray-500 dark:text-gray-400">設定をどのタイプで説明するか選んでください</p>
                <ul class="my-4 space-y-3">
                    <li>
                      <div class="flex items-center p-3 text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow dark:bg-gray-600 dark:hover:bg-gray-500 dark:text-white">
                        <%= link_to '文章', new_work_work_block_path(@work, blockable_type: "Sentence", tab: 3), class: 'flex-1 ml-3 whitespace-nowrap' %>
                      </div>
                    </li>
                    <li>
                      <div class="flex items-center p-3 text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow dark:bg-gray-600 dark:hover:bg-gray-500 dark:text-white">
                        <%= link_to '画像', new_work_work_block_path(@work, blockable_type: "Medium", tab: 3), class: 'flex-1 ml-3 whitespace-nowrap' %>
                      </div>
                    </li>
                    <li>
                      <div class="flex items-center p-3 text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow dark:bg-gray-600 dark:hover:bg-gray-500 dark:text-white">
                        <%= link_to 'ツイート', new_work_work_block_path(@work, blockable_type: "Embed", tab: 3), class: 'flex-1 ml-3 whitespace-nowrap' %>
                      </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/work_blocks/edit.html.erb
<div class="w-full max-w-xs mx-auto">
  <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">

    <div class="text-3xl font-bold pb-4">
      <h1>設定を編集する</h1>
    </div>

      <% if @work_block.sentence? %>
        <!-- 文章編集フォーム -->
        <div class="p-4 bg-gray-50 rounded-lg dark:bg-gray-800">
          <p class="text-sm text-gray-500 dark:text-gray-400">
          <a href="/?content=sentence"></a>
            <%= form_with model: @sentence, url: work_work_block_path(@work, @work_block), local: true do |f|%>
              <div>
                <%= f.hidden_field :blockable_type, :value => Sentence %>
                <%= f.label :body, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
                <%= f.text_area :body, rows: 4, class: "mb-3 block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
              </div>
              <%= f.submit '送信', class: "text-white bg-gray-900 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
            <% end %>
          </p>
        </div>

      <% elsif @work_block.medium? %>
        <!-- 画像編集フォーム -->
        <div class="p-4 bg-gray-50 rounded-lg dark:bg-gray-800" id="settings" role="tabpanel" aria-labelledby="settings-tab">
            <p class="text-sm text-gray-500 dark:text-gray-400">
              <%= form_with model: @medium, url: work_work_block_path(@work, @work_block), local: true do |f|%>
                <div>
                  <%= f.hidden_field :blockable_type, :value => Medium %>
                  <%= f.label :name, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
                  <%= f.file_field :name, rows: 4, class: "mb-3 block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"%>
                </div>
                <%= f.submit '送信', class: "text-white bg-gray-900 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
              <% end %>
            </p>
        </div>

      <% elsif @work_block.embed? %>
        <!-- 埋め込み編集フォーム -->
        <div class=" p-4 bg-gray-50 rounded-lg dark:bg-gray-800">
          <p class="text-sm text-gray-500 dark:text-gray-400">
            <%= form_with model: @embed, url: work_work_block_path(@work, @work_block), local: true do |f|%>
              <div>
                <%= f.hidden_field :blockable_type, :value => Embed %>
                <%= f.label :identifier, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
                <%= f.text_field :identifier, rows: 4, class: "mb-3 block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "ツイートのurlをコピペして下さい。ツイートの共有ボタンからツイートのリンクをコピーできます。" %>
              </div>
              <%= f.submit '送信', class: "text-white bg-gray-900 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
            <% end %>
          </p>
        </div>
      <% end %>

  </div>
</div>

app/views/work_blocks/new.html.erb
<div class="w-full max-w-xs mx-auto">
  <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">

    <div class="text-3xl font-bold pb-4">
      <h1>設定を追加する</h1>
    </div>

    <% if @blockable_type  == 'Sentence' %>
      <!-- 文章新規登録フォーム -->
      <div class=" p-4 bg-gray-50 rounded-lg dark:bg-gray-800">
        <p class="text-sm text-gray-500 dark:text-gray-400">
        <a href="/?content=sentence"></a>
          <%= form_with model: @sentence, url: work_work_blocks_path(@work, @work_block), local: true do |f|%>
            <div>
              <%= f.hidden_field :blockable_type, :value => Sentence %>
              <%= f.hidden_field :tab, :value => @tab %>
              <%= f.label :body, Sentence.human_attribute_name(:body), class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
              <%= f.text_area :body, rows: 4, class: "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
            </div>
            <%= f.submit '送信', class: "mt-3 text-white bg-gray-900 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
          <% end %>
        </p>
      </div>

    <% elsif @blockable_type  == 'Medium' %>
      <!-- 画像新規登録フォーム -->
      <div class="p-4 bg-gray-50 rounded-lg dark:bg-gray-800" id="settings" role="tabpanel" aria-labelledby="settings-tab">
          <p class="text-sm text-gray-500 dark:text-gray-400">
            <%= form_with model: @medium, url: work_work_blocks_path(@work, @work_block), local: true do |f|%>
              <div>
                <%= f.hidden_field :blockable_type, :value => Medium %>
                <%= f.hidden_field :tab, :value => @tab %>
                <%= f.label :name, Medium.human_attribute_name(:name), class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
                <%= f.file_field :name, multiple: true, include_hidden: false, rows: 4, class: "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"%>
              </div>
              <%= f.submit '送信', class: "mt-3 text-white bg-gray-900 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
            <% end %>
          </p>
      </div>

    <% elsif @blockable_type  == 'Embed' %>
      <!-- 埋め込み新規登録フォーム -->
      <div class=" p-4 bg-gray-50 rounded-lg dark:bg-gray-800">
        <p class="text-sm text-gray-500 dark:text-gray-400">
          <%= form_with model: @embed, url: work_work_blocks_path(@work, @work_block), local: true do |f|%>
            <div>
              <%= f.hidden_field :blockable_type, :value => Embed %>
              <%= f.hidden_field :tab, :value => @tab %>
              <%= f.label :identifier, Embed.human_attribute_name(:identifier), class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
              <%= f.text_area :identifier, rows: 4, class: "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "ツイートのurlをコピペして下さい。　ツイートの共有ボタンからツイートのリンクをコピーできます。" %>
            </div>
            <%= f.submit '送信', class: "mt-3 text-white bg-gray-900 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
          <% end %>
        </p>
      </div>
    <% end %>

  </div>
</div>